-- Easypaisa Payment Gateway Database Migration
-- This script creates the necessary tables and columns for Easypaisa integration

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create easypaisa_transactions table
CREATE TABLE IF NOT EXISTS easypaisa_transactions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
    store_id VARCHAR(50) NOT NULL,
    payment_token VARCHAR(255),
    transaction_type VARCHAR(10) NOT NULL CHECK (transaction_type IN ('MA', 'OTC')),
    transaction_amount DECIMAL(10, 2) NOT NULL,
    mobile_number VARCHAR(15),
    email_address VARCHAR(255),
    transaction_datetime TIMESTAMP WITH TIME ZONE,
    token_expiry_datetime TIMESTAMP WITH TIME ZONE,
    response_code VARCHAR(10),
    response_desc TEXT,
    transaction_status VARCHAR(20) DEFAULT 'pending' CHECK (transaction_status IN ('pending', 'success', 'failed', 'expired')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_easypaisa_order_id ON easypaisa_transactions(order_id);
CREATE INDEX IF NOT EXISTS idx_easypaisa_payment_token ON easypaisa_transactions(payment_token);
CREATE INDEX IF NOT EXISTS idx_easypaisa_status ON easypaisa_transactions(transaction_status);
CREATE INDEX IF NOT EXISTS idx_easypaisa_created_at ON easypaisa_transactions(created_at DESC);

-- Add Easypaisa-specific columns to orders table if they don't exist
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'orders' AND column_name = 'easypaisa_payment_token') THEN
        ALTER TABLE orders ADD COLUMN easypaisa_payment_token VARCHAR(255);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                   WHERE table_name = 'orders' AND column_name = 'easypaisa_transaction_type') THEN
        ALTER TABLE orders ADD COLUMN easypaisa_transaction_type VARCHAR(10);
    END IF;
END $$;

-- Create function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_easypaisa_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for updated_at
DROP TRIGGER IF EXISTS trigger_easypaisa_updated_at ON easypaisa_transactions;
CREATE TRIGGER trigger_easypaisa_updated_at
    BEFORE UPDATE ON easypaisa_transactions
    FOR EACH ROW
    EXECUTE FUNCTION update_easypaisa_updated_at();

-- Create view for easy transaction monitoring
CREATE OR REPLACE VIEW easypaisa_transaction_summary AS
SELECT 
    et.id,
    et.order_id,
    o.order_number,
    et.payment_token,
    et.transaction_type,
    et.transaction_amount,
    et.mobile_number,
    et.transaction_status,
    et.response_code,
    et.response_desc,
    et.created_at,
    et.token_expiry_datetime,
    CASE 
        WHEN et.token_expiry_datetime < NOW() AND et.transaction_status = 'pending' 
        THEN true 
        ELSE false 
    END AS is_expired
FROM easypaisa_transactions et
LEFT JOIN orders o ON et.order_id = o.id
ORDER BY et.created_at DESC;

-- Add comment to table
COMMENT ON TABLE easypaisa_transactions IS 'Stores all Easypaisa payment transactions including Mobile Account (MA) and Over-the-Counter (OTC) payments';

-- Add comments to columns
COMMENT ON COLUMN easypaisa_transactions.transaction_type IS 'Payment type: MA (Mobile Account) or OTC (Over-the-Counter)';
COMMENT ON COLUMN easypaisa_transactions.payment_token IS 'Unique payment token generated by Easypaisa for OTC payments';
COMMENT ON COLUMN easypaisa_transactions.transaction_status IS 'Current status: pending, success, failed, or expired';
COMMENT ON COLUMN easypaisa_transactions.response_code IS 'Easypaisa API response code (0000=success, 0001=pending, 0002=failed)';

-- Grant necessary permissions (adjust role name as needed)
-- GRANT SELECT, INSERT, UPDATE ON easypaisa_transactions TO your_app_role;
-- GRANT SELECT ON easypaisa_transaction_summary TO your_app_role;

-- Success message
DO $$
BEGIN
    RAISE NOTICE 'Easypaisa migration completed successfully!';
    RAISE NOTICE 'Created table: easypaisa_transactions';
    RAISE NOTICE 'Created view: easypaisa_transaction_summary';
    RAISE NOTICE 'Added columns to orders table: easypaisa_payment_token, easypaisa_transaction_type';
END $$;
